# Nixpacks Configuration for Core Meme Platform Monorepo

# Explicitly declare Node.js provider
providers = ["node"]

[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = [
  # Install pnpm and use npx to run it in the same command
  'npm install -g pnpm@10.13.1 && npx pnpm@10.13.1 install --frozen-lockfile'
]

[phases.build]  
cmds = [
  # Build shared library first using npx
  'cd shared && npx pnpm@10.13.1 build && cd ..',
  # Install turbo and build all services using npx
  'npm install -g turbo && npx turbo run build',
  # Install PM2 for production runtime
  'npm install -g pm2'
]

[start]
cmd = 'pm2-runtime start ecosystem.config.js --env production'

[variables]
NODE_ENV = 'production'