# Nixpacks Configuration for Core Meme Platform Monorepo
# Deploys all services as a single Coolify application using PM2

[phases.setup]
# Install Node.js 20, pnpm, and required system dependencies
nixPkgs = ['nodejs_20', 'pnpm']
aptPkgs = ['python3', 'make', 'g++', 'git']

[phases.install]
# Install all workspace dependencies and build shared library
cmds = [
  'pnpm install',
  'pnpm --filter @core-meme/shared build'
]

[phases.build]
# Build all services using Turborepo for optimal caching
cmds = [
  'npx turbo run build',
  'mkdir -p logs',
  'npm install -g pm2@latest'
]
cacheDirectories = ['node_modules', '**/node_modules', '.pnpm-store', '.turbo']

[start]
cmd = 'pm2-runtime start ecosystem.config.js --env production'

[variables]
NODE_ENV = 'production'
CI = 'true'