version: '3.8'

services:
  core-api:
    build: .
    container_name: core-api-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LOG_LEVEL=info
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - core-network
    volumes:
      - ./logs:/app/logs

  redis:
    image: redis:7-alpine
    container_name: core-api-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - core-network

networks:
  core-network:
    driver: bridge

volumes:
  redis-data: